development:
  host: '127.0.0.1'
  port: 9042
  keyspace: cassandra_development
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

test:
  host: '127.0.0.1'
  port: 9042
  keyspace: cassandra_test
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

production:
  host: '127.0.0.1'
  port: 9042
  keyspace: cassandra_production
  max_retries: 3
  retry_delay: 0.5
  newrelic: false
